const routes = {
  vc: ["/", "/notif", "/users", "/programmes", "/message"],
  Admin: ["/", "/notif", "users", "/programme", "/message", "/header"],
  "Vice Chancellor": [
    "/",
    "/notifications",
    "/messages",
    "/status",
    "/external-status",
    "/existing-status",
  ],
  "Pro-Vice Chancellor(Academic and Student Affairs)": [
    "/",
    "/notifications",
    "/messages",

    "/status",
    "/existing-status",
    "/external-status",
  ],
  "Pro-Vice Chancellor(Research Innovation and Development)": [
    "/",
    "/notifications",
    "message",
    "/status",

    "/existing-status",
    "/external-status",
  ],
  Registrar: [
    "/",
    "/notifications",
    "/message",
    "/status",
    "/external-status",
    "/existing-status",
  ],
  "Director of Academic Affairs": [
    "/",
    "/notifications",
    "message",
    "/status",
    "/external-status",
    "/existing-status",
  ],
  "Provost of College": [
    "/",
    "/notifications",
    "/message",
    "/status",
    "/external-status",
    "/existing-status",
  ],
  "Director of Academic Quality Assurance": [
    "/",
    "/notifications",
    "/message",
    "/status",
    "/external-status",
    "/existing-status",
  ],
  "Dean of School/Director": [
    "/",
    "/notifications",
    "/message",
    "/status",
    "/external-status",
    "/existing-status",
  ],
  "Head of Department": [
    "/",
    "/notifications",
    "/exisupdate",
    "/extupdate",
    "/update",
    "/ugreq",
    "/status",
    "/newform",
    "/external-status",
    "/existing-status",
    "/existingreq",
    "/programme",
    "nctereq",
    "nabreq",
  ],
};

export default routes;
